from __future__ import annotations

import importlib.util
import pathlib
import tempfile
import unittest


SCRIPT_PATH = pathlib.Path(__file__).resolve().parents[1] / "prepare-changelog-release.py"
SPEC = importlib.util.spec_from_file_location("prepare_changelog_release", SCRIPT_PATH)
assert SPEC is not None and SPEC.loader is not None
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


def write_fragment(path: pathlib.Path, front_matter: str, body: str) -> None:
    path.write_text(f"---\n{front_matter}\n---\n\n{body}\n", encoding="utf-8")


class PrepareChangelogReleaseTests(unittest.TestCase):
    def test_parse_fragment_accepts_quotes_comments_and_extra_keys(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            fragment = pathlib.Path(tmp_dir) / "123.fix.md"
            write_fragment(
                fragment,
                "\n".join(
                    [
                        "# generated by a helper",
                        'kind: "fix"',
                        "note: internal metadata",
                        "pr: 'https://github.com/0xMiden/miden-vm/pull/123'",
                        "crate: miden-processor",
                    ]
                ),
                "Fix a user-facing behavior in one concise sentence.",
            )

            parsed = MODULE.parse_fragment(fragment)

        self.assertEqual(parsed["kind"], "fix")
        self.assertEqual(parsed["crate"], "miden-processor")
        self.assertEqual(parsed["pr_number"], 123)
        self.assertEqual(
            parsed["body"], "Fix a user-facing behavior in one concise sentence."
        )

    def test_collect_fragments_sorts_by_pr_number_then_filename(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            unreleased = pathlib.Path(tmp_dir)
            write_fragment(
                unreleased / "10.fix.md",
                "kind: fix\npr: https://github.com/0xMiden/miden-vm/pull/10",
                "Third in sort order.",
            )
            write_fragment(
                unreleased / "2.change.md",
                "kind: change\npr: https://github.com/0xMiden/miden-vm/pull/2",
                "First in sort order.",
            )
            write_fragment(
                unreleased / "2.fix.md",
                "kind: fix\npr: https://github.com/0xMiden/miden-vm/pull/2",
                "Second in sort order.",
            )

            original_unreleased_dir = MODULE.UNRELEASED_DIR
            MODULE.UNRELEASED_DIR = unreleased
            try:
                fragments = MODULE.collect_fragments()
            finally:
                MODULE.UNRELEASED_DIR = original_unreleased_dir

        self.assertEqual(
            [fragment["filename"] for fragment in fragments],
            ["2.change.md", "2.fix.md", "10.fix.md"],
        )

    def test_archive_fragments_flushes_old_batches_and_keeps_gitkeep(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = pathlib.Path(tmp_dir)
            archive_root = root / "archive"
            archive_root.mkdir()
            (archive_root / ".gitkeep").write_text("", encoding="utf-8")
            (archive_root / "0.22.0").mkdir()
            (archive_root / "0.22.0" / "stale.fix.md").write_text("stale", encoding="utf-8")
            source = root / "12.fix.md"
            write_fragment(
                source,
                "kind: fix\npr: https://github.com/0xMiden/miden-vm/pull/12",
                "Archived after release prep.",
            )
            fragments = [MODULE.parse_fragment(source)]

            original_archive_dir = MODULE.ARCHIVE_DIR
            MODULE.ARCHIVE_DIR = archive_root
            try:
                MODULE.archive_fragments("0.23.0", fragments)
            finally:
                MODULE.ARCHIVE_DIR = original_archive_dir

            self.assertFalse(source.exists())
            self.assertTrue((archive_root / ".gitkeep").exists())
            self.assertFalse((archive_root / "0.22.0").exists())
            self.assertTrue((archive_root / "0.23.0" / "12.fix.md").exists())


if __name__ == "__main__":
    unittest.main()
