//! Asynchronous settlement of an MVM deferred obligation by the PVM verifier.

use std::sync::Arc;

use miden_assembly::{Assembler, Linkage};
use miden_core::{
    Felt, Word,
    advice::AdviceMap,
    deferred::DeferredState,
    events::{EventId, EventName},
    program::{ExecutionClaim, proof_request_key},
    proof::{DeferredProof, ExecutionProof, HashFunction},
};
use miden_core_lib::{CoreLibrary, PVM_PROOF_REQUEST_EVENT_NAME};
use miden_debug_types::{Location, SourceFile, SourceSpan};
use miden_precompiles_prover::{
    ProveDeferredStateError,
    masm_verifier::{MasmVerifierInputError, generate_masm_verifier_inputs},
    prove_deferred_state,
};
use miden_processor::{
    BaseHost, DefaultHost, ExecutionOptions, ExecutionOutput, FastProcessor, FutureMaybeSend, Host,
    LoadedMastForest, ProcessorState, ProgramInfo, StackInputs, SyncHost,
    advice::{AdviceInputs, AdviceMutation, AdviceStack},
    event::EventError,
};
use miden_prover::{ProvingOptions, prove_partial_sync};
use miden_verifier::{Verifier, recursive::RecursiveVerifierInputs};

use crate::{helpers::masm_push_word, support::ecdsa::valid_fixture};

#[tokio::test(flavor = "current_thread")]
async fn ecdsa_deferred_obligation_is_settled_end_to_end() {
    let core_lib = CoreLibrary::default();
    let (partial_proof, claim) = prove_partial_ecdsa_execution(&core_lib);
    assert!(
        matches!(partial_proof.deferred_proof(), DeferredProof::Wire(_)),
        "partial proving must preserve the ECDSA deferred state as wire material",
    );

    let miden_proof = partial_proof.miden_proof().clone();
    let (_, unsettled) = Verifier::new()
        .verify_partial(&partial_proof, &claim)
        .expect("the MVM proof must authenticate its deferred obligation");
    let deferred_root = unsettled.root();

    let settlement =
        run_settlement_in_masm(&core_lib, &partial_proof, &claim, unsettled.into_state())
            .await
            .expect("the awaited MVM-to-PVM handoff must settle the authenticated deferred root");
    assert!(
        matches!(
            &settlement.deferred_proof,
            DeferredProof::Stark { public_root, .. } if *public_root == deferred_root
        ),
        "the awaited proof must expose the root authenticated by the MVM verifier",
    );
    assert_eq!(
        settlement.output.stack.get_num_elements(4),
        vec![Felt::ZERO; 4],
        "settlement must consume the deferred root rather than return it",
    );

    let final_proof = ExecutionProof::new(miden_proof, settlement.deferred_proof);
    Verifier::new()
        .verify(&final_proof, &claim)
        .expect("native final verification must accept the proof generated by the event");
}

fn prove_partial_ecdsa_execution(core_lib: &CoreLibrary) -> (ExecutionProof, ExecutionClaim) {
    let fixture = valid_fixture();

    let source = format!(
        "
        begin
            {}
            {}
            exec.::miden::core::crypto::dsa::ecdsa_k256_keccak::verify
        end
        ",
        masm_push_word(&fixture.message),
        masm_push_word(&fixture.public_key_commitment),
    );
    let program = Assembler::default()
        .with_package(core_lib.package(), Linkage::Dynamic)
        .expect("core library must link")
        .assemble_program("ecdsa_deferred_settlement", source)
        .expect("ECDSA settlement fixture must assemble")
        .unwrap_program();
    let mut host = DefaultHost::default()
        .with_library(core_lib)
        .expect("core library must load into the host");
    let mut advice_stack = AdviceStack::new();
    advice_stack.append_elements(fixture.advice);
    let stack_inputs = StackInputs::default();
    let (stack_outputs, proof) = prove_partial_sync(
        &program,
        stack_inputs,
        AdviceInputs::default().with_stack(advice_stack),
        &mut host,
        ExecutionOptions::default(),
        ProvingOptions::new(HashFunction::Poseidon2),
    )
    .expect("ECDSA execution must produce a partial MVM proof");
    let claim =
        ExecutionClaim::from_program_info(ProgramInfo::from(program), stack_inputs, stack_outputs);

    (proof, claim)
}

struct SettlementResult {
    output: ExecutionOutput,
    deferred_proof: DeferredProof,
}

async fn run_settlement_in_masm(
    core_lib: &CoreLibrary,
    partial_proof: &ExecutionProof,
    claim: &ExecutionClaim,
    deferred_state: DeferredState,
) -> Result<SettlementResult, miden_processor::ExecutionError> {
    let vm = RecursiveVerifierInputs::for_request(
        core_lib.recursive_verifier_root(),
        partial_proof,
        claim,
    )
    .expect("partial MVM proof must adapt to recursive-verifier advice");
    let (advice_inputs, claim_commitment) = vm.into_parts();
    assert!(advice_inputs.stack().is_empty(), "the MVM proof stream must be map-backed");

    let stack_inputs = StackInputs::new(claim_commitment.as_elements())
        .expect("claim commitment must fit the stack");
    let program = assemble_settlement_program(core_lib);
    let mut host = PvmSettlementHost::new(core_lib, deferred_state);

    let output =
        FastProcessor::new_with_options(stack_inputs, advice_inputs, ExecutionOptions::default())
            .expect("failed to construct FastProcessor")
            .execute(&program, &mut host)
            .await?;
    let deferred_proof = host
        .deferred_proof
        .take()
        .expect("successful settlement must retain the generated proof");

    Ok(SettlementResult { output, deferred_proof })
}

fn assemble_settlement_program(core_lib: &CoreLibrary) -> miden_processor::Program {
    let source = "
        use miden::core::sys
        use miden::core::stark::utils
        use miden::core::sys::pvm
        use miden::core::sys::vm

        begin
            dupw
            procref.vm::verify_vm_proof exec.sys::build_proof_request_key
            adv.push_mapval dropw
            exec.vm::verify_vm_proof

            # Accept the MVM proof while retaining its authenticated deferred root.
            swapw
            exec.utils::conjectured_security_level
            u32lt.96 assertz
            drop drop

            # Execution awaits the host here. request_proof installs the returned package on the
            # advice stack; the response remains untrusted until verify_proof passes.
            exec.pvm::request_proof
            exec.pvm::verify_proof
            exec.utils::conjectured_security_level
            u32lt.96 assertz
            drop drop
            exec.sys::truncate_stack
        end
        ";

    Assembler::default()
        .with_package(core_lib.package(), Linkage::Dynamic)
        .expect("core library must link")
        .assemble_program("async_pvm_settlement", source)
        .expect("async settlement program must assemble")
        .unwrap_program()
}

struct PvmSettlementHost {
    inner: DefaultHost,
    event_name: EventName,
    expected_verifier_root: Word,
    deferred_state: DeferredState,
    deferred_proof: Option<DeferredProof>,
}

impl PvmSettlementHost {
    fn new(core_lib: &CoreLibrary, deferred_state: DeferredState) -> Self {
        let inner = DefaultHost::default()
            .with_library(core_lib)
            .expect("core library must load into the settlement host");
        Self {
            inner,
            event_name: PVM_PROOF_REQUEST_EVENT_NAME,
            expected_verifier_root: core_lib.pvm_recursive_verifier_root(),
            deferred_state,
            deferred_proof: None,
        }
    }
}

impl BaseHost for PvmSettlementHost {
    fn get_label_and_source_file(
        &self,
        location: &Location,
    ) -> (SourceSpan, Option<Arc<SourceFile>>) {
        BaseHost::get_label_and_source_file(&self.inner, location)
    }

    fn resolve_event(&self, event_id: EventId) -> Option<&EventName> {
        if event_id == PVM_PROOF_REQUEST_EVENT_NAME.to_event_id() {
            Some(&self.event_name)
        } else {
            BaseHost::resolve_event(&self.inner, event_id)
        }
    }
}

impl Host for PvmSettlementHost {
    fn get_mast_forest(
        &self,
        node_digest: &Word,
    ) -> impl FutureMaybeSend<Option<LoadedMastForest>> {
        let forest = SyncHost::get_mast_forest(&self.inner, node_digest);
        async move { forest }
    }

    fn on_event(
        &mut self,
        process: &ProcessorState<'_>,
    ) -> impl FutureMaybeSend<Result<Vec<AdviceMutation>, EventError>> {
        async move {
            let event_id = EventId::from_felt(process.get_stack_item(0));
            if event_id != PVM_PROOF_REQUEST_EVENT_NAME.to_event_id() {
                return SyncHost::on_event(&mut self.inner, process);
            }

            let verifier_root = process.get_stack_word(1);
            let requested_root = process.get_stack_word(5);
            if verifier_root != self.expected_verifier_root {
                return Err(SettlementEventError::VerifierRootMismatch {
                    requested: verifier_root,
                    expected: self.expected_verifier_root,
                }
                .into());
            }
            if requested_root != self.deferred_state.root() {
                return Err(SettlementEventError::RootMismatch {
                    requested: requested_root,
                    available: self.deferred_state.root(),
                }
                .into());
            }

            let proof_key = proof_request_key(verifier_root, requested_root);
            if process.advice_provider().map().get(&proof_key).is_some() {
                return Err(SettlementEventError::PackageAlreadyLoaded.into());
            }

            // Exercise a genuine suspension point. A production host can await a remote prover or
            // run the CPU-bound prover on its blocking pool before returning these mutations.
            tokio::task::yield_now().await;
            let deferred_proof =
                prove_deferred_state(&self.deferred_state, HashFunction::Poseidon2)
                    .map_err(SettlementEventError::Proving)?;
            let (proof, public_root) = match &deferred_proof {
                DeferredProof::Stark { proof, public_root } => (proof, *public_root),
                DeferredProof::Empty | DeferredProof::Wire(_) => {
                    return Err(SettlementEventError::InvalidProofShape.into());
                },
            };
            if public_root != requested_root {
                return Err(SettlementEventError::RootMismatch {
                    requested: requested_root,
                    available: public_root,
                }
                .into());
            }

            let package = generate_masm_verifier_inputs(proof, requested_root)
                .map_err(SettlementEventError::Advice)?
                .into_request_package(verifier_root)
                .map_err(SettlementEventError::Advice)?;
            let advice_map = AdviceMap::from_iter(package.advice_map);
            let merkle_nodes = package.store.inner_nodes();
            self.deferred_proof = Some(deferred_proof);

            Ok(vec![
                AdviceMutation::extend_map(advice_map),
                AdviceMutation::extend_merkle_store(merkle_nodes),
            ])
        }
    }
}

#[derive(Debug, thiserror::Error)]
enum SettlementEventError {
    #[error("requested verifier root {requested:?} does not match expected root {expected:?}")]
    VerifierRootMismatch { requested: Word, expected: Word },
    #[error("requested deferred root {requested:?} does not match available root {available:?}")]
    RootMismatch { requested: Word, available: Word },
    #[error("a PVM proof package was already loaded before the settlement event")]
    PackageAlreadyLoaded,
    #[error("PVM proof generation failed: {0}")]
    Proving(#[source] ProveDeferredStateError),
    #[error("non-empty deferred state did not produce a STARK-backed proof")]
    InvalidProofShape,
    #[error("PVM recursive-verifier advice construction failed: {0}")]
    Advice(#[source] MasmVerifierInputError),
}
